name: Print GitHub Context

on:
  pull_request

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Print the full GitHub context as JSON
      - name: Print GitHub Context
        run: |
          echo '${{ toJSON(github) }}'
